[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "py-ts-tune"
version = "0.1.0"
description = "Python module for parsing EFI Analytics TunerStudio tune files."
readme = "README.md"
license = "BSD-2-Clause"
packages = [{ include = "ts_tune" }]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"

[tool.poetry.group.dev.dependencies]
pytest = "^9.1.1"

[tool.pytest.ini_options]
testpaths = ["tests"]
