[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "py-ts-tune"
version = "0.1.0"
description = "Python module for parsing EFI Analytics TunerStudio tune files."
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }

[tool.setuptools.packages.find]
include = ["ts_tune*"]
